"""Model constants package.

This package contains constants specific to different model modules
organized by functionality.
"""

from .user_permissions_management_constants import (
    VALID_PERMISSION_TYPES,
    PERMISSION_FIELDS,
    PERMISSION_TYPE_ERROR,
    USER_ID_ERROR,
    DUPLICATE_PERMISSIONS_ERROR,
    NO_PERMISSIONS_PROVIDED_ERROR,
    INVALID_USER_REFERENCE_ERROR,
    DEFAULT_PERMISSION_VALUE,
    READ_PERMISSIONS,
    WRITE_PERMISSIONS,
    DESTRUCTIVE_PERMISSIONS,
    EXECUTION_PERMISSIONS,
    ADMIN_PERMISSIONS,
    PERMISSION_CATEGORIES,
    PERMISSION_HIERARCHY,
    USER_ID_MIN_VALUE,
    PERMISSION_FIELD_MAX_LENGTH,
    USER_PERMISSIONS_TABLE_NAME,
    USER_PERMISSIONS_FOREIGN_KEY,
    USER_PERMISSIONS_CASCADE_DELETE,
    MIN_BULK_PERMISSIONS,
    MAX_BULK_PERMISSIONS,
    DEFAULT_GRANTED_ONLY,
    DEFAULT_INCLUDE_INACTIVE_USERS,
    PERMISSION_DESCRIPTION_MAX_LENGTH,
    PERMISSION_NAME_MAX_LENGTH,
    MAX_PERMISSIONS_PER_USER,
    MAX_USERS_PER_BULK_OPERATION,
    PERMISSION_LEVELS,
    BASIC_PERMISSIONS,
    STANDARD_PERMISSIONS,
    ADVANCED_PERMISSIONS,
    ADMIN_LEVEL_PERMISSIONS,
    PERMISSION_TEMPLATES,
    PERMISSION_GRANT_SUCCESS,
    PERMISSION_REVOKE_SUCCESS,
    BULK_PERMISSION_SUCCESS,
    PERMISSION_ALREADY_EXISTS,
    PERMISSION_NOT_EXISTS,
    PERMISSION_STATUS_ACTIVE,
    PERMISSION_STATUS_INACTIVE,
    PERMISSION_STATUS_PENDING,
    PERMISSION_STATUS_REVOKED,
    VALID_PERMISSION_STATUSES,
    PERMISSIONS_RESPONSE_LIMIT,
    DEFAULT_PERMISSIONS_PAGE_SIZE,
    MAX_PERMISSIONS_PAGE_SIZE,
)

__all__ = [
    # Permission types and fields
    "VALID_PERMISSION_TYPES",
    "PERMISSION_FIELDS",
    
    # Error messages
    "PERMISSION_TYPE_ERROR",
    "USER_ID_ERROR", 
    "DUPLICATE_PERMISSIONS_ERROR",
    "NO_PERMISSIONS_PROVIDED_ERROR",
    "INVALID_USER_REFERENCE_ERROR",
    
    # Default values
    "DEFAULT_PERMISSION_VALUE",
    
    # Permission categories
    "READ_PERMISSIONS",
    "WRITE_PERMISSIONS",
    "DESTRUCTIVE_PERMISSIONS", 
    "EXECUTION_PERMISSIONS",
    "ADMIN_PERMISSIONS",
    "PERMISSION_CATEGORIES",
    "PERMISSION_HIERARCHY",
    
    # Field constraints
    "USER_ID_MIN_VALUE",
    "PERMISSION_FIELD_MAX_LENGTH",
    "PERMISSION_DESCRIPTION_MAX_LENGTH",
    "PERMISSION_NAME_MAX_LENGTH",
    
    # Database constants
    "USER_PERMISSIONS_TABLE_NAME",
    "USER_PERMISSIONS_FOREIGN_KEY",
    "USER_PERMISSIONS_CASCADE_DELETE",
    
    # Validation constants
    "MIN_BULK_PERMISSIONS",
    "MAX_BULK_PERMISSIONS",
    "MAX_PERMISSIONS_PER_USER",
    "MAX_USERS_PER_BULK_OPERATION",
    
    # Permission levels and groups
    "PERMISSION_LEVELS",
    "BASIC_PERMISSIONS",
    "STANDARD_PERMISSIONS",
    "ADVANCED_PERMISSIONS",
    "ADMIN_LEVEL_PERMISSIONS",
    "PERMISSION_TEMPLATES",
    
    # Success/Error messages
    "PERMISSION_GRANT_SUCCESS",
    "PERMISSION_REVOKE_SUCCESS",
    "BULK_PERMISSION_SUCCESS",
    "PERMISSION_ALREADY_EXISTS",
    "PERMISSION_NOT_EXISTS",
    
    # Status constants
    "PERMISSION_STATUS_ACTIVE",
    "PERMISSION_STATUS_INACTIVE",
    "PERMISSION_STATUS_PENDING",
    "PERMISSION_STATUS_REVOKED",
    "VALID_PERMISSION_STATUSES",
    
    # API and query defaults
    "DEFAULT_GRANTED_ONLY",
    "DEFAULT_INCLUDE_INACTIVE_USERS",
    "PERMISSIONS_RESPONSE_LIMIT",
    "DEFAULT_PERMISSIONS_PAGE_SIZE",
    "MAX_PERMISSIONS_PAGE_SIZE",
]
