"""Initial migration

Revision ID: 3373e01d40b9
Revises: 
Create Date: 2025-08-02 22:39:51.497199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3373e01d40b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_uuid', sa.String(length=50), nullable=False),
    sa.Column('resource_name', sa.String(length=200), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_name')
    )
    op.create_index('idx_created_on', 'resources', ['created_on'], unique=False)
    op.create_index('idx_resource_name', 'resources', ['resource_name'], unique=False)
    op.create_index('idx_resource_uuid', 'resources', ['resource_uuid'], unique=False)
    op.create_index('idx_updated_on', 'resources', ['updated_on'], unique=False)
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_resource_uuid'), 'resources', ['resource_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_resource_uuid'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_index('idx_updated_on', table_name='resources')
    op.drop_index('idx_resource_uuid', table_name='resources')
    op.drop_index('idx_resource_name', table_name='resources')
    op.drop_index('idx_created_on', table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
